options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

steps:
  # Step 1: Build Docker image using Artifact Registry naming
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/imperial-medium-461815-j1/recommender/anime-recommender'
      - '.'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/imperial-medium-461815-j1/recommender/anime-recommender'

  # Step 3: Deploy to Cloud Run with secrets attached
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint : 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'anime-recommender'
      - '--image=us-central1-docker.pkg.dev/imperial-medium-461815-j1/recommender/anime-recommender'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--update-secrets=GROQ_API_KEY=GROQ_API_KEY:latest,neo_username=neo_username:latest,neo_password=neo_password:latest,LANGCHAIN_API_KEY=LANGCHAIN_API_KEY:latest'

  # Step 4: Ensure public access to Cloud Run (automates IAM binding)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint : 'gcloud'
    args:
      - 'run'
      - 'services'
      - 'add-iam-policy-binding'
      - 'anime-recommender'
      - '--region=us-central1'
      - '--platform=managed'
      - '--member=allUsers'
      - '--role=roles/run.invoker'

timeout: '12000s'
